// All renderer imports for browser shell composition stay at this boundary.
export { ContribController as DesktopController } from '@/app/contrib/controller'
export { ContribWiring, WiredPane } from '@/app/contrib/wiring'
export { SidebarProvider } from '@/components/ui/sidebar'
export { Codicon } from '@/components/ui/codicon'
export { ContribRender, ContribBoundary } from '@/contrib/react/boundary'
export { useContributions } from '@/contrib/react/use-contributions'
export { contributedRoutes, ROUTES_AREA, APP_ROUTES, navigateToWorkspacePage } from '@/app/routes'
export { $selectedStoredSessionId, $gatewayState } from '@/store/session'
export { $pinnedSessionIds, $sidebarPinsOpen, setSidebarPinsOpen } from '@/store/layout'
export { $activeGatewayProfile, $profiles, $showAllProfiles, ALL_PROFILES, refreshProfiles, selectProfile, setShowAllProfiles } from '@/store/profile'
export { runImportProfileFlow } from '@/store/profile-share'
export { CreateProfileDialog } from '@/app/profiles/create-profile-dialog'
export { $selectedBot } from '@/plugins/hermes-bots/bot-state'
export { $layoutTree, revealTreePane } from '@/components/pane-shell/tree/store'
export { findGroupOfPane } from '@/components/pane-shell/tree/model'
export { LayoutTreeRoot } from '@/components/pane-shell/tree/renderer'
export { SessionTileCloseConfirm } from '@/app/chat/session-tile'
export type { TitlebarTool } from '@/app/shell/titlebar-controls'

export { BrowserWorkspace } from './browser-workspace'
export { BrowserPanelButton } from './browser-panel-button'
